### ISSUE TITLE
Initialize TiKV CDC / BR repo

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#40]
# Motivation
Initialize TiKV CDC / BR repo, to provide CDC feature for TiKV.
Related issue: https://github.com/tikv/tikv/issues/11745
Related RFC: https://github.com/tikv/rfcs/pull/86

# Tasks
- [x] CDC
  - [x] Initialize CDC codes from https://github.com/pingcap/tiflow/tree/v5.5.0-alpha to `tikv/migration/cdc`.
  - [x] Build Locally
  - [x] Unit Test Locally ([ref](https://github.com/pingcap/tiflow/blob/master/tests/integration_tests/README.md#unit-test))
  - [x] Integration Test Locally (tikv-tikv ONLY, [ref](https://github.com/pingcap/tiflow/blob/master/tests/integration_tests/README.md#integration-test))
  - [x] Build in CI ([ref](https://github.com/pingcap/tiflow/blob/master/docs/ci/command.md))
  - [x] Unit in CI ([ref](https://github.com/pingcap/tiflow/blob/master/docs/ci/command.md))
  - [x] Integration Test in CI (tikv-tikv ONLY, [ref](https://github.com/pingcap/tiflow/blob/master/docs/ci/command.md))
- [x] BR
  - [x] Initialize BR codes from https://github.com/pingcap/tidb/tree/v5.5.0-alpha/br to `tikv/migration/br`.
  - [x] Build Locally
  - [x] Unit Test Locally
  - [x] Integration Test Locally
  - [x] Build in CI
  - [x] Unit Test in CI
  - [x] Integration Test in CI

**Comment by zz-jason** [comment]
license check failed, please fix it once the code migration is finished ASAP: https://github.com/tikv/migration/issues/47

**Comment by zz-jason** [comment]
@marsishandsome could you help to move the `pom.xml` file to `online-bulk-load` and `sst-data-source`? so that each tool can be compiled inside its subdirectory individually, clean the root directory to simply collect the source codes for different migration-related tools.
