### ISSUE TITLE
TiKV CDC Development Tasks

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#48]
# TiKV CDC Development Tasks

Related issue: https://github.com/tikv/tikv/issues/11745
Related RFC: https://github.com/tikv/rfcs/pull/86

# Tasks
- [x] Core data structure in ETCD
  - [x] raw changefeed
  - [x] raw task (a part of a changefeed, for one processor)
  - [x] ETCD path planning
- [x] Owner
  - [x] New `changefeed` for RawKV
  - [x] Delete table `changefeed`
- [ ] Scheduler
  - [ ] New scheduler for `Key Span`
  - [x] Delete table scheduler
- [x] Capture
  - [x] Support rawkv `changefeed`
  - [x] Delete support of table `changefeed`
- [x] Processor
  - [x] New processor for Key Span
- [x] Sink
  - [x] TiKV Sink
- [x] Command line
  - [x] cdc cli
- [ ] Others
  - [ ] Upgrade dependencies
- [ ] TiUP support
- [ ] Metrics
  - [ ] New Grafana board for TiKV-CDC
  - [ ] Determine metrics (ref to TiCDC metrics)
- [ ] Tests
  - [ ] Integration tests
  - [ ] E2E tests

# Development Guide
1. Choose a task you are interested in.
2. File a ISSUE for the task.
3. Fix the ISSUE by PR (also refer to CONTRIBUTING guide).
4. Get the PR merged.
