### ISSUE TITLE
TiKV BR Development Tasks

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#67]
## TiKV BR Development Tasks

Close: #66 
RFC: https://github.com/tikv/rfcs/pull/86

## Tasks
- [x] TiKV-BR
  - [x] Fix CI error (ref: #57, find CI error [here](https://github.com/tikv/migration/pull/54)) #68 #70 
  - [x] Cherrypick https://github.com/pingcap/tidb/pull/32612 #77 
  - [x] Support RawKV API V2 https://github.com/tikv/migration/pull/75, https://github.com/tikv/migration/pull/91
  - [x] Support migration from RawKV API V1/TTL to V2 https://github.com/tikv/migration/pull/75, https://github.com/tikv/migration/pull/91
  - [x] Add checksum https://github.com/tikv/migration/pull/91
- [x] TiKV
  - [x] Write development proposal & discuss with DP team
  - [x] Support RawKV API V2 https://github.com/tikv/tikv/pull/12303
  - [x] Support migration from RawKV API V1/TTL to V2 https://github.com/tikv/tikv/pull/12303
  - [x] Add checksum (ref [raw_checksum] (https://github.com/tikv/tikv/blob/869b953e798cabf29872fd17d526a7061437aec2/src/storage/mod.rs#L2425)) https://github.com/tikv/tikv/pull/12303
  - [x] Fix https://github.com/tikv/tikv/issues/12015: https://github.com/tikv/tikv/pull/12303

## Reference
TiKV components related to backup & restore:
* components/backup: for backup
* components/sst_importer: for restore
* [split_region interface](https://github.com/tikv/tikv/blob/9a43faf4da20389a4e2c262ee8ab8b369a3bfec4/src/server/service/kv.rs#L758): for pre-splitting regions before restore

Some merged PR related:
* https://github.com/tikv/tikv/issues/10940
* https://github.com/tikv/tikv/issues/11041
* https://github.com/tikv/tikv/pull/11664

**Comment by pingyu** [comment]
@zz-jason @haojinming PTAL~

**Comment by pingyu** [comment]
All sub tasks are done.
